const cfg=window.BOXPAK_CONFIG;
const validConfig=cfg&&cfg.supabaseUrl&&!cfg.supabaseUrl.startsWith("PASTE_")&&cfg.supabaseAnonKey&&!cfg.supabaseAnonKey.startsWith("PASTE_");
const client=validConfig?supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
const $=id=>document.getElementById(id);let currentRows=[],searchTimer;
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const timeText=v=>v?String(v).replace("T"," ").slice(11,19):"";
function durationText(a,b){if(!a||!b)return "";const seconds=Math.max(0,(new Date(b)-new Date(a))/1000);return `${Math.floor(seconds/3600)} giờ ${Math.floor(seconds%3600/60)} phút`;}
function showApp(session){$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");$("userEmail").textContent=session.user.email;loadData();}
function showLogin(){$("appView").classList.add("hidden");$("loginView").classList.remove("hidden");}
const selectedEmployee=()=>$("employeeCode").value.trim().toUpperCase();
async function loadData(){
  $("loadStatus").textContent="Đang tải...";const date=$("workDate").value;const site=$("siteCode").value.trim();const employee=selectedEmployee();
  let query=client.from("attendance_daily").select("*").eq("work_date",date).eq("site_code",site).order("first_seen");
  if(employee)query=query.ilike("employee_code",employee);
  const {data,error}=await query;
  if(error){$("loadStatus").textContent="Lỗi: "+error.message;return;}currentRows=data||[];
  $("attendanceBody").innerHTML=currentRows.length?currentRows.map(r=>`<tr><td>${escapeHtml(r.employee_code)}</td><td class="name">${escapeHtml(r.full_name)}</td><td>${escapeHtml(r.department)}</td><td>${timeText(r.first_seen)}</td><td>${timeText(r.last_seen)}</td><td>${durationText(r.first_seen,r.last_seen)}</td><td>${r.recognition_count}</td></tr>`).join(""):`<tr><td colspan="7" class="empty">Chưa có dữ liệu</td></tr>`;
  $("totalCount").textContent=currentRows.length;$("deptCount").textContent=new Set(currentRows.map(r=>r.department)).size;
  $("lastUpdate").textContent=currentRows.length?timeText(currentRows.reduce((a,b)=>a.last_seen>b.last_seen?a:b).last_seen):"--:--";$("loadStatus").textContent=employee?(currentRows.length?`Đã tìm thấy ${employee}`:`Không có dữ liệu của ${employee} trong ngày này`):`${currentRows.length} công nhân`;
  const info=$("employeeInfo");
  if(employee&&currentRows.length){const r=currentRows[0];info.innerHTML=`<div><span>NHÂN VIÊN ĐANG LỌC</span><strong>${escapeHtml(r.employee_code)} — ${escapeHtml(r.full_name)}</strong></div><div><span>BỘ PHẬN</span><strong>${escapeHtml(r.department||"—")}</strong></div><button id="clearEmployee" class="secondary">Bỏ lọc</button>`;info.classList.remove("hidden");$("clearEmployee").onclick=()=>{$("employeeCode").value="";loadData();};}else info.classList.add("hidden");
}
function escapeHtml(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function downloadCsv(rows,from,to){const employee=selectedEmployee();const head=["Ngày","MSNV","Họ tên","Bộ phận","Giờ vào","Giờ ra","Tổng số giờ phút có mặt"];const lines=[head,...rows.map(r=>[r.work_date,r.employee_code,r.full_name,r.department,timeText(r.first_seen),timeText(r.last_seen),durationText(r.first_seen,r.last_seen)])];const csv="\ufeff"+lines.map(row=>row.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=`cham-cong-${employee||$("siteCode").value}-${from}-den-${to}.csv`;a.click();URL.revokeObjectURL(a.href);}
function openExport(){const selected=$("workDate").value||today();const employee=selectedEmployee();$("exportFrom").value=selected;$("exportTo").value=selected;$("exportStatus").textContent="";$("exportScope").textContent=employee?`Chỉ xuất dữ liệu của nhân viên ${employee}`:"Xuất dữ liệu của tất cả nhân viên";$("exportDialog").showModal();}
async function exportRange(){const from=$("exportFrom").value,to=$("exportTo").value,site=$("siteCode").value.trim(),employee=selectedEmployee();if(!from||!to){$("exportStatus").textContent="Hãy chọn đủ từ ngày và đến ngày.";return;}if(from>to){$("exportStatus").textContent="Từ ngày không được sau đến ngày.";return;}$("exportStatus").textContent="Đang chuẩn bị dữ liệu...";let query=client.from("attendance_daily").select("*").eq("site_code",site).gte("work_date",from).lte("work_date",to).order("work_date").order("employee_code");if(employee)query=query.ilike("employee_code",employee);const {data,error}=await query;if(error){$("exportStatus").textContent="Lỗi: "+error.message;return;}if(!data?.length){$("exportStatus").textContent=employee?`Không có dữ liệu của ${employee} trong khoảng ngày đã chọn.`:"Không có dữ liệu trong khoảng ngày đã chọn.";return;}downloadCsv(data,from,to);$("exportDialog").close();}
$("workDate").value=today();$("siteCode").value=cfg?.defaultSite||"NHA_MAY_A";
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();if(!client){$("loginError").textContent="Website chưa được cấu hình Supabase.";return;}$("loginError").textContent="Đang đăng nhập...";const {data,error}=await client.auth.signInWithPassword({email:$("email").value,password:$("password").value});if(error){$("loginError").textContent=error.message;return;}$("loginError").textContent="";showApp(data.session);});
$("logoutBtn").onclick=async()=>{await client.auth.signOut();showLogin();};$("refreshBtn").onclick=loadData;$("exportBtn").onclick=openExport;$("downloadRangeBtn").onclick=exportRange;$("workDate").onchange=loadData;$("employeeCode").addEventListener("input",()=>{clearTimeout(searchTimer);searchTimer=setTimeout(loadData,350);});$("employeeCode").addEventListener("keydown",e=>{if(e.key==="Enter"){clearTimeout(searchTimer);loadData();}});
if(client)client.auth.getSession().then(({data})=>data.session?showApp(data.session):showLogin());
